/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "faiawsxesvfzbveqfsjl"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhaWF3c3hlc3ZmemJ2ZXFmc2psIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAwNDk2MzEsImV4cCI6MjA4NTYyNTYzMX0.L76HyAmknkMI-imVJ1Ardcd-99IX7OwojfHJtDDiseg"